spring:
  cloud:
    stream:
      bindings:
        myMessage:
          #对消息进行分组：当前项目部署多个实例时，只会有一个实例处理消息
          group: order
          content-type: application/json
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 10.57.211.134
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://10.57.211.134:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    getProductInfoList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

logging:
  level:
    org.springframework.cloud.openfeign: debug
    com.imooc.order.controller.HystrixController: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

env:
  dev
girl:
  name: yan
  age: 25
